print("Welcome to the Tip Calculator")
bill = float(input("What was the total bill?\n$"))
tip= int(input("What percentage tip would you like to give? 10,12 or 15?\n"))
tip_in_percent= 1+(tip/100)
people= int(input("How many people to split the bill?\n"))
splitted_bill= bill*(tip_in_percent/people)
# final_amount= round(splitted_bill,2)
final_amount= "{:.2f}".format(splitted_bill)
message= (f"Each person should pay: ${final_amount}")
print(message)